LibraryManagementSystem/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from LibraryManagementSystem import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls'))
]

if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from library import views
app_name = 'library'
urlpatterns = [
    path('',views.homeview,name = 'homeview'),
    url(r'^login/$',views.user_login, name = 'login'),
    url(r'^signout/$',views.signout, name='signout'),
    url(r'^register/$',views.register, name='register'),
    url(r'^profile=(?P<profile>[\w]+)$', views.user_profile, name = 'user_profile'),
    url(r'^book=(?P<book_id>[\w]+)$',views.book_detail,name = 'book_detail'),
]

library/models.py
from datetime import datetime

from django.db import models

# Create your models here.
from django.contrib.auth.models import User
import uuid


class UserProfile(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=100, blank=False, null=False)
    last_name = models.CharField(max_length=100, blank=False, null=False)
    phone = models.BigIntegerField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    profile_pic = models.ImageField(upload_to='profile_pic', default='default.png')
    fine = models.IntegerField(default=0)


    def __str__(self):
        string = "{} {}".format(self.first_name,self.last_name)
        return string


class Category(models.Model):
    name = models.CharField(max_length=500, blank=False, null=False)
    description = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=500, blank=False, null=False)
    author = models.CharField(max_length=500, blank=False, null=False)
    publisher = models.CharField(max_length=500, blank=False, null=False)
    edition = models.CharField(max_length=500, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    language = models.CharField(max_length=500, blank=False, null=False)
    isbn = models.IntegerField()
    year = models.IntegerField()
    pages = models.IntegerField()
    abstract = models.CharField(max_length=1000, blank=False, null=False)
    photo = models.ImageField(upload_to='book_photos',default='media/default.png')
    quantity = models.IntegerField(default=10)


    def __str__(self):
        return self.name


class Inventory(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    order_id = models.UUIDField(unique=True, default=uuid.uuid4)
    issue_date = models.DateTimeField(default=datetime.now())
    return_date = models.DateTimeField(blank=True, null=True)
    fine = models.IntegerField(default=0)
    status = models.BooleanField(default=False)

    def __str__(self):
        return str(self.order_id)

library/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import PasswordInput

from library.models import UserProfile, Book


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=PasswordInput)

    class Meta():
        model = User
        fields = ('username','password','email')

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['password'].help_text = ''
        self.fields['email'].help_text = ''

class UserProfileForm(forms.ModelForm):

    class Meta():
        model = UserProfile
        fields = ('first_name','last_name','phone','address','profile_pic')

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].help_text = ''
        self.fields['last_name'].help_text = ''
        self.fields['phone'].help_text = ''
        self.fields['address'].help_text = ''
        self.fields['profile_pic'].help_text = ''

class BookForm(forms.ModelForm):

    class Meta():
        model = Book
        fields = '__all__'

library/views.py
from datetime import datetime

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect


# Create your views here.
from library.forms import UserForm, UserProfileForm
from library.models import Book, Inventory, UserProfile


def homeview(request):
    if request.method == 'POST':
        user = UserProfile.objects.get(user = request.user)
        book = Book.objects.get(isbn=request.POST['borrow'])
        if book.quantity == 0:
            return HttpResponse('Book out of stock')
        book.quantity -= 1
        book.save()
        inventory = Inventory()
        inventory.book = book
        inventory.user = user
        inventory.save()
    books = Book.objects.all()
    context = {'books':books}
    return render(request,'library/home.html',context)

def signout(request):
    logout(request)
    return render(request, 'library/home.html')

def user_login(request):
    if request.method == 'POST':
        if 'login' in request.POST:
            username = request.POST['uname']
            password = request.POST['pass']
            user = authenticate(username = username,password = password)
            if user:
                if user.is_active:
                    login(request,user)
                    return redirect('library:homeview')
                else:
                    return HttpResponse('Account inactive')
            else:
                print("Failed login at username: {} and password: {}".format(username,password))
                return HttpResponse('Invalid login')

    else:
        return render(request, 'library/login.html')

def register(request):
    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileForm(request.POST,request.FILES)
        print("UserForm.errors: {} \n ProfileForm.errors: {}".format(user_form.errors,profile_form.errors))
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)

            profile.user = request.user
            profile.save()
            return render(request,'library/home.html')
        else:
            return HttpResponse('{} {}'.format(user_form.errors,profile_form.errors))

    elif request.method == 'GET':
        user_form = UserForm(auto_id=False)
        profile_form = UserProfileForm(auto_id=False)
        return render(request,'library/register.html',{'user_form':user_form,'profile_form':profile_form})

def user_profile(request,profile):
    if request.method == 'POST':
        id = request.POST['return']
        inv = Inventory.objects.get(order_id=id)
        book = Book.objects.get(id = inv.book.id)
        book.quantity += 1
        book.save()
        inv.return_date = datetime.now()
        days = inv.return_date - inv.issue_date
        fine = 0
        if days.days> 30:
            if days.days < 35:
                for i in range(days.days - 30):
                    fine += 5
            else:
                for i in range(days.days - 30):
                    fine += 5
                for i in range(35,days.days):
                    fine += 10
        inv.fine = fine
        inv.status = True
        inv.save()



    user = UserProfile.objects.get(user = User.objects.get(username=profile))
    inventorys = Inventory.objects.filter(user = user)
    return render(request,'library/user_profile.html',{'user':user,'inventorys':inventorys})

def book_detail(request,book_id):
    book = Book.objects.get(id=book_id)
    return render(request,'library/book_detail.html',{'book':book})

library/templates/library/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style>
    .sticky{
        position: fixed;
  top: 0;
  width: 100%;
    }

</style>
</head>
  <body>
    <nav class="navbar navbar-default sticky-top sticky" >
      <div class="container">


{# Django Home Link / Admin Link / Register Link#}

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}

              <ul class="nav navbar-nav navbar-right">
            <li><a class="navbar-link" href="{% url 'library:signout' %}">Logout</a></li>
              <li><a class="navbar-link" href="{% url 'library:user_profile' user %}"><img style="border-radius: 50%" src="{{ profile.profile_pic.url }}" alt="profile-pic" width="30px" height="30px"  ></a></li>
              </ul>
          {% else %}
              <ul class="nav navbar-nav">
            <li><a class="navbar-link" href="{% url 'library:register' %}">Register</a></li>
            <li><a class="navbar-link" href="{% url 'library:login' %}">Login</a></li>

          {% endif %}

</ul>
      </div>
    </nav>
    <br>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

library/templates/library/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ book.name }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <style>
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    padding: 5px;
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: black;
  font-size: xx-large;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #4CAF50;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

a{
    color: #ffffff;
}

.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
  position: absolute;
  right: 25px;
  top: 0;
  color: #000;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: red;
  cursor: pointer;
}

/* Add Zoom Animation */
.animate {
  -webkit-animation: animatezoom 0.6s;
  animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
  from {-webkit-transform: scale(0)}
  to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
  from {transform: scale(0)}
  to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}

.button:hover {
  background-color: #555;
}
</style>

</head>
<body>

<div class="container" align="center">
    <div class="well well-sm">
        <div class="title">{{ book.name }}</div>
        <p><strong>Author: </strong>{{ book.author }}</p>
        <p><strong>ISBN: </strong>{{ book.isbn }}</p>
        <p><strong>Category: </strong>{{ book.category }}</p>
        <p><strong>Year: </strong>{{ book.year }}</p>
        <p><strong>Pages: </strong>{{ book.pages }}</p>
        <p><strong>Publisher: </strong>{{ book.publisher }}</p>
        <p><strong>Language: </strong>{{ book.language }}</p>
        <p><strong>Abstract: </strong>{{ book.abstract }}</p>
        <p><strong>Quantity: </strong>{{ book.quantity }}</p>

    </div>
</div>

</body>
</html>

library/templates/library/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style>
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    padding: 5px;
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}
</style>
</head>
<body>
<nav class="navbar navbar-default sticky-top sticky" style="background-color: #f5dd5d">
      <nav class="container">
{% if user.is_authenticated %}
              <ul class="nav navbar-nav navbar-right">
            <li><a class="navbar-link" href="{% url 'library:signout' %}">Logout</a></li>
              <li><a class="navbar-link" href="{% url 'library:user_profile' user %}"><img style="border-radius: 50%" src="{{ profile.profile_pic.url }}" alt="profile-pic" width="30px" height="30px"  ></a></li>
              </ul>

          {% else %}
              <ul class="nav navbar-nav">
            <li><a class="navbar-link" href="{% url 'library:register' %}">Register</a></li>
            <li><a class="navbar-link" href="{% url 'library:login' %}">Login</a></li>

          {% endif %}
      </ul>
          </nav>
      </nav>
    {% if user.is_authenticated %}


        <br>
        <div class="container">
        <div class="row">
        {% for book in books %}
            {% if book.quantity > 0 %}
            <div class="column">
    <div class="card" align="center">
      <img src="{{ book.photo.url }}" alt="bla" style="width:100%">
      <div class="container">
        <h2>{{ book.name }}</h2>
        <p class="title">{{ book.author }}</p>
        <p>{{ book.abstract }}</p>
        <p>{{ book.category }}</p>
        <form method="post" action="">{% csrf_token %}<button name="borrow" value="{{ book.isbn }}">Borrow</button></form>
      </div>
    </div>
  </div>
            {% endif %}
        {% endfor %}
        </div>
        </div>
    {% endif %}

</body>
</html>











{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#<meta name="viewport" content="width=device-width, initial-scale=1">#}
{#<style>#}
{#html {#}
{#  box-sizing: border-box;#}
{#}#}
{##}
{#*, *:before, *:after {#}
{#  box-sizing: inherit;#}
{#}#}
{##}
{#.column {#}
{#  float: left;#}
{#  width: 33.3%;#}
{#  margin-bottom: 16px;#}
{#  padding: 0 8px;#}
{#}#}
{##}
{#@media screen and (max-width: 650px) {#}
{#  .column {#}
{#    width: 100%;#}
{#    display: block;#}
{#  }#}
{#}#}
{##}
{#.card {#}
{#  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);#}
{#}#}
{##}
{#.container {#}
{#  padding: 0 16px;#}
{#}#}
{##}
{#.container::after, .row::after {#}
{#  content: "";#}
{#  clear: both;#}
{#  display: table;#}
{#}#}
{##}
{#.title {#}
{#  color: grey;#}
{#}#}
{##}
{#.button {#}
{#  border: none;#}
{#  outline: 0;#}
{#  display: inline-block;#}
{#  padding: 8px;#}
{#  color: white;#}
{#  background-color: #000;#}
{#  text-align: center;#}
{#  cursor: pointer;#}
{#  width: 100%;#}
{#}#}
{##}
{#.button:hover {#}
{#  background-color: #555;#}
{#}#}
{#</style>#}
{#</head>#}
{#<body>#}
{##}
{#<h2>Responsive "Meet The Team" Section</h2>#}
{#<p>Resize the browser window to see the effect.</p>#}
{#<br>#}
{##}
{#<div class="row">#}
{#  <div class="column">#}
{#    <div class="card">#}
{#      <img src="/w3images/team1.jpg" alt="Jane" style="width:100%">#}
{#      <div class="container">#}
{#        <h2>Jane Doe</h2>#}
{#        <p class="title">CEO & Founder</p>#}
{#        <p>Some text that describes me lorem ipsum ipsum lorem.</p>#}
{#        <p>example@example.com</p>#}
{#        <p><button class="button">Contact</button></p>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{##}
{#  <div class="column">#}
{#    <div class="card">#}
{#      <img src="/w3images/team2.jpg" alt="Mike" style="width:100%">#}
{#      <div class="container">#}
{#        <h2>Mike Ross</h2>#}
{#        <p class="title">Art Director</p>#}
{#        <p>Some text that describes me lorem ipsum ipsum lorem.</p>#}
{#        <p>example@example.com</p>#}
{#        <p><button class="button">Contact</button></p>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#  <div class="column">#}
{#    <div class="card">#}
{#      <img src="/w3images/team3.jpg" alt="John" style="width:100%">#}
{#      <div class="container">#}
{#        <h2>John Doe</h2>#}
{#        <p class="title">Designer</p>#}
{#        <p>Some text that describes me lorem ipsum ipsum lorem.</p>#}
{#        <p>example@example.com</p>#}
{#        <p><button class="button">Contact</button></p>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#</div>#}
{##}
{#</body>#}
{#</html>#}
{##}
{##}
{##}
{##}
{#Name: {{ book.name }}#}
{#            <br>#}
{#            Author: {{ book.author }}#}
{#            <br>#}
{#            <form method="post" action="">#}
{#            {% csrf_token %}#}
{#                <button name="borrow" value="{{ book.isbn }}">Borrow</button>#}
{#            </form>#}

library/templates/library/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password], input[type=email], input[type=number], textarea  {
  width: 97%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button , input[type=submit]{
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 75%;
}

button:hover {
  opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
  position: relative;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
  position: absolute;
  right: 25px;
  top: 0;
  color: #000;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: red;
  cursor: pointer;
}

/* Add Zoom Animation */
.animate {
  -webkit-animation: animatezoom 0.6s;
  animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
  from {-webkit-transform: scale(0)}
  to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
  from {transform: scale(0)}
  to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
</style>
</head>
<body>





<div align="center">
<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>
</div>

<div id="id01" class="modal" align="center">

  <form class="modal-content animate" action="" method="post">
      {% csrf_token %}
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
    </div>

    <div class="container">
     Username: <input type="text" name="uname">
        <br/>
        Password: <input type="password" name="pass">
        <br/>
        <input type="submit" name="login" value="Login">
    </div>


  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>
</html>

library/templates/library/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Register User</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password], input[type=email], input[type=number], textarea {
  width: 97%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button , input[type=submit]{
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 75%;
}

button:hover {
  opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
  position: relative;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
  position: absolute;
  right: 25px;
  top: 0;
  color: #000;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: red;
  cursor: pointer;
}

/* Add Zoom Animation */
.animate {
  -webkit-animation: animatezoom 0.6s;
  animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
  from {-webkit-transform: scale(0)}
  to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
  from {transform: scale(0)}
  to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
</style>
</head>
<body>
<div align="center">
<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Register</button>
</div>

<div id="id01" class="modal" align="center" style="padding: 2px">

  <form class="modal-content animate" action="" method="post">
      {% csrf_token %}
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
    </div>
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="submit" value="Register">
    <div class="container">

    </div>


  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>


</body>
</html>